LIBRARY ieee;
USE ieee.std_logic_1164.ALL;

ENTITY BLOCOFUNCOES IS
	PORT (
		A : IN STD_LOGIC_VECTOR(7 DOWNTO 0);
		B : IN STD_LOGIC_VECTOR(7 DOWNTO 0);

		S_1 : OUT STD_LOGIC_VECTOR(7 DOWNTO 0); --FUNCAO 1
		Cout_1 : OUT STD_LOGIC;

		S_2 : OUT STD_LOGIC_VECTOR(7 DOWNTO 0); --FUNCAO 2 
		Cout_2 : OUT STD_LOGIC;

		S_3 : OUT STD_LOGIC_VECTOR(7 DOWNTO 0); --FUNCAO 3 
		Cout_3 : OUT STD_LOGIC;

		S_4 : OUT STD_LOGIC_VECTOR(7 DOWNTO 0); --FUNCAO 4
		Cout_4 : OUT STD_LOGIC;

		S_5 : OUT STD_LOGIC_VECTOR(7 DOWNTO 0); --FUNCAO 5
		Cout_5 : OUT STD_LOGIC;

		S_8 : OUT STD_LOGIC_VECTOR(7 DOWNTO 0); --FUNCAO 8
		Cout_8 : OUT STD_LOGIC;

		S_9 : OUT STD_LOGIC_VECTOR(7 DOWNTO 0); --FUNCAO 9

		S_10 : OUT STD_LOGIC_VECTOR(7 DOWNTO 0); --FUNCAO 10

		S_11 : OUT STD_LOGIC_VECTOR(7 DOWNTO 0); --FUNCAO 11

		S_12 : OUT STD_LOGIC_VECTOR(7 DOWNTO 0); --FUNCAO 12

		S_13 : OUT STD_LOGIC_VECTOR(7 DOWNTO 0); --FUNCAO 13

		S_14 : OUT STD_LOGIC_VECTOR(7 DOWNTO 0); --FUNCAO 14

		S_15 : OUT STD_LOGIC_VECTOR(7 DOWNTO 0) --FUNCAO 15

	);
END BLOCOFUNCOES;

ARCHITECTURE CKT OF BLOCOFUNCOES IS
	COMPONENT Somador8Bits IS --FUNCAO 1
		PORT (
			A : IN STD_LOGIC_VECTOR(7 DOWNTO 0);
			B : IN STD_LOGIC_VECTOR(7 DOWNTO 0);
			Cin : IN STD_LOGIC;
			Cout : OUT STD_LOGIC;
			S : OUT STD_LOGIC_VECTOR(7 DOWNTO 0)
		);
	END COMPONENT;

	COMPONENT Subtrator8Bits IS --FUNCAO 2
		PORT (
			A : IN STD_LOGIC_VECTOR(7 DOWNTO 0);
			B : IN STD_LOGIC_VECTOR(7 DOWNTO 0);
			Bn : BUFFER STD_LOGIC_VECTOR(7 DOWNTO 0);
			Cout : OUT STD_LOGIC;
			S : OUT STD_LOGIC_VECTOR(7 DOWNTO 0)
		);
	END COMPONENT;

	COMPONENT mult_8bit IS --FUNCAO 3
		PORT (
			a, b : IN STD_LOGIC_VECTOR(7 DOWNTO 0);
			s : OUT STD_LOGIC_VECTOR(7 DOWNTO 0);
			c_out : OUT STD_LOGIC
		);
	END COMPONENT;

	COMPONENT Incrementador8Bits IS --FUNCAO 4
		PORT (
			A : IN STD_LOGIC_VECTOR(7 DOWNTO 0);
			Cout : OUT STD_LOGIC;
			S : OUT STD_LOGIC_VECTOR(7 DOWNTO 0)
		);
	END COMPONENT;

	COMPONENT Decrementador8Bits IS --FUNCAO 5
		PORT (
			A : IN STD_LOGIC_VECTOR(7 DOWNTO 0);
			Cout : OUT STD_LOGIC;
			S : OUT STD_LOGIC_VECTOR(7 DOWNTO 0)
		);
	END COMPONENT;

	COMPONENT shr_8bit IS --FUNCAO 8 
		PORT (
			e : IN STD_LOGIC_VECTOR(7 DOWNTO 0);
			s : IN STD_LOGIC_VECTOR(2 DOWNTO 0);
			z : OUT STD_LOGIC_VECTOR(7 DOWNTO 0)
		);
	END COMPONENT;

	COMPONENT shl_8bit IS --FUNCAO 9
		PORT (
			e : IN STD_LOGIC_VECTOR(7 DOWNTO 0);
			s : IN STD_LOGIC_VECTOR(2 DOWNTO 0);
			z : OUT STD_LOGIC_VECTOR(7 DOWNTO 0);
			c_out : OUT STD_LOGIC
		);
	END COMPONENT;

	COMPONENT SWP IS --FUNCAO 10
		PORT (
			A : IN STD_LOGIC_VECTOR(7 DOWNTO 0);
			S : OUT STD_LOGIC_VECTOR(7 DOWNTO 0)
		);
	END COMPONENT;

	COMPONENT SWA IS --FUNCAO 11
		PORT (
			A : IN STD_LOGIC_VECTOR(7 DOWNTO 0);
			S : OUT STD_LOGIC_VECTOR(7 DOWNTO 0)
		);
	END COMPONENT;

	COMPONENT PORTA_AND IS --FUNCAO 12
		PORT (
			A : IN STD_LOGIC_VECTOR(7 DOWNTO 0);
			B : IN STD_LOGIC_VECTOR(7 DOWNTO 0);
			S : OUT STD_LOGIC_VECTOR(7 DOWNTO 0)
		);
	END COMPONENT;

	COMPONENT PORTA_OR IS --FUNCAO 13
		PORT (
			A : IN STD_LOGIC_VECTOR(7 DOWNTO 0);
			B : IN STD_LOGIC_VECTOR(7 DOWNTO 0);
			S : OUT STD_LOGIC_VECTOR(7 DOWNTO 0)
		);
	END COMPONENT;

	COMPONENT PORTA_XOR IS --FUNCAO 14
		PORT (
			A : IN STD_LOGIC_VECTOR(7 DOWNTO 0);
			B : IN STD_LOGIC_VECTOR(7 DOWNTO 0);
			S : OUT STD_LOGIC_VECTOR(7 DOWNTO 0)
		);
	END COMPONENT;

	COMPONENT PORTA_NOT IS --FUNCAO 15
		PORT (
			A : IN STD_LOGIC_VECTOR(7 DOWNTO 0);
			S : OUT STD_LOGIC_VECTOR(7 DOWNTO 0)
		);
	END COMPONENT;

	-- sinais internos
	SIGNAL Cin_1 : STD_LOGIC := '0'; --CIN SOMA
	SIGNAL Bn_sub : STD_LOGIC_VECTOR(7 DOWNTO 0); --COMPLEMENTO DE 1

BEGIN
	U1 : Somador8Bits --FUNCAO 1
	PORT MAP(A => A, B => B, Cin => Cin_1, Cout => Cout_1, S => S_1);

	U2 : Subtrator8Bits --FUNCAO 2
	PORT MAP(A => A, B => B, Bn => Bn_sub, Cout => Cout_2, S => S_2);

	U3 : mult_8bit --FUNCAO 3
	PORT MAP(A => A, B => B, c_out => Cout_3, S => S_3);

	U4 : Incrementador8Bits --FUNCAO 4
	PORT MAP(A => A, Cout => Cout_4, S => S_4);

	U5 : Decrementador8Bits --FUNCAO 5
	PORT MAP(A => A, Cout => Cout_5, S => S_5);

	U8 : shl_8bit -- FUNCAO 8
	PORT MAP(e => A, s => B(2 DOWNTO 0), c_out => Cout_8, z => S_8);

	U9 : shr_8bit -- FUNCAO 9
	PORT MAP(e => A, s => B(2 DOWNTO 0), z => S_9);

	U10 : SWP --FUNCAO10
	PORT MAP(A => A, S => S_10);

	U11 : SWA --FUNCAO11
	PORT MAP(A => A, S => S_11);

	U12 : PORTA_AND --FUNCAO12
	PORT MAP(A => A, B => B, S => S_12);

	U13 : PORTA_OR --FUNCAO13
	PORT MAP(A => A, B => B, S => S_13);

	U14 : PORTA_XOR --FUNCAO14
	PORT MAP(A => A, B => B, S => S_14);

	U15 : PORTA_NOT --FUNCAO15
	PORT MAP(A => A, S => S_15);

END CKT;