LIBRARY ieee;
USE ieee.std_logic_1164.ALL;

ENTITY PORTA_XOR IS
	PORT (
		A : IN STD_LOGIC_VECTOR(7 DOWNTO 0);
		B : IN STD_LOGIC_VECTOR(7 DOWNTO 0);
		S : OUT STD_LOGIC_VECTOR(7 DOWNTO 0));
END PORTA_XOR;

ARCHITECTURE porta_xor OF PORTA_XOR IS

BEGIN

	S(7 DOWNTO 0) <= A(7 DOWNTO 0) XOR B(7 DOWNTO 0);

END porta_xor;