LIBRARY ieee;
USE ieee.std_logic_1164.ALL;

ENTITY PORTA_OR IS
	PORT (
		A : IN STD_LOGIC_VECTOR(7 DOWNTO 0);
		B : IN STD_LOGIC_VECTOR(7 DOWNTO 0);
		S : OUT STD_LOGIC_VECTOR(7 DOWNTO 0));
END PORTA_OR;

ARCHITECTURE porta_or OF PORTA_OR IS

BEGIN

	S(7 DOWNTO 0) <= A(7 DOWNTO 0) OR B(7 DOWNTO 0);

END porta_or;