LIBRARY ieee;
USE ieee.std_logic_1164.ALL;

ENTITY PORTA_NOT IS
	PORT (
		A : IN STD_LOGIC_VECTOR(7 DOWNTO 0);
		S : OUT STD_LOGIC_VECTOR(7 DOWNTO 0));
END PORTA_NOT;

ARCHITECTURE porta_not OF PORTA_NOT IS

BEGIN

	S(7 DOWNTO 0) <= NOT A(7 DOWNTO 0);

END porta_not;